<?php echo $this->doctype()."\n";?>

<html>

	<head>
	<link rel="shortcut icon" type="image/png" href="<?php echo $this->basePath().'/favicon.ico'; ?>"/>
<link rel="shortcut icon" type="image/png" href=<?php echo $this->basePath().'/favicon.ico'; ?>"/>
		<?php echo $this->headTitle()."\n";?>

		<?php echo $this->headLink()."\n" ?>

		<?php echo $this->headScript()."\n" ?>

		<script>
		
	
		</script>

	</head>

	<body>
	<?php echo $this->content; ?>

	</body>

</html>