
<link href="<?php echo  $this->basePath('css/admin/bootstrap.css'); ?>" media="screen" rel="stylesheet" type="text/css" />
<link href="<?php echo  $this->basePath('css/admin/style.css'); ?>" media="screen" rel="stylesheet" type="text/css" />

<link href="<?php echo  $this->basePath('css/admin/bootstrap-theme.min.css'); ?>" media="screen" rel="stylesheet" type="text/css" >
<link href="<?php echo $this->basePath('css/admin/font-awesome.min.css') ?>" media="screen" rel="stylesheet" type="text/css" >
<link href="<?php echo $this->basePath('css/admin/ionicons.min.css') ; ?>" media="screen" rel="stylesheet" type="text/css" >
<link href="<?php echo $this->basePath('css/admin/AdminLTE.min.css') ; ?>" media="screen" rel="stylesheet" type="text/css" >
<link href="<?php echo $this->basePath('css/admin/square/blue.css') ; ?>" media="screen" rel="stylesheet" type="text/css" >
<body class="hold-transition login-page">
<div class="login-box">
  <div class="login-logo">
    <a href="<?php echo $this->basePath('admin');?>"><img src="<?php echo $this->basePath('/images/logo-new.png'); ?>" alt="Admin Logo"> </a>
  </div>
  <!-- /.login-logo -->
  <div class="login-box-body">
    <p class="login-box-msg">Sign in to start your session</p>

    <form name="form-signin" id="form-signin" method="POST" action="<?php echo $this->basePath('admin/index/loginpost'); ?>">
	
   
      <div class="form-group has-feedback">
		<input type="text" class="form-control" name="admin_username" placeholder="Username" value="<?php echo $this->username;?>" required>
        <span class="glyphicon glyphicon-envelope form-control-feedback"></span>
      </div>
      <div class="form-group has-feedback">
		<input type="password" class="form-control" placeholder="Password" name="admin_password" value="<?php echo $this->password;?>" required>
        <span class="glyphicon glyphicon-lock form-control-feedback"></span>
      </div>
	<div class="row">
		<div class="col-xs-4">
		  <button type="submit" class="btn btn-primary btn-block btn-flat">Sign In</button>
		</div>
	</div>
   </form>
  </div>
  </div> <!-- /container -->
  </body>
<script type="text/javascript" src="<?php echo $this->basePath('js/admin/jquery.js') ?>"></script>
<script type="text/javascript" src="<?php echo $this->basePath('js/admin/bootstrap.min.js') ?>"></script>
<script type="text/javascript" src="<?php echo $this->basePath('js/admin/icheck.min.js') ?>"></script>
<script>
  $(function () {
	$('input').iCheck({
	  checkboxClass: 'icheckbox_square-blue',
	  radioClass: 'iradio_square-blue',
	  increaseArea: '20%' // optional
	});
  });
</script>